'use client';
import {useEffect,useState} from 'react';
import * as XLSX from 'xlsx';
import {getSupabase} from '../../lib/supabase';

const clean=v=>v==null?'':String(v).trim();
function mapStatus(v){const s=clean(v).toLowerCase();if(['bertemu','sudah bertemu','sudah visit','berhasil ditemui','ditemui','yes','ya'].includes(s))return 'Bertemu';if(['tidak bertemu','belum bertemu','tidak ditemui','tidak ditemukan','menolak bertemu','no','tidak'].includes(s))return 'Tidak Bertemu';return '';}
export default function Admin(){
 const [sb,setSb]=useState(null),[session,setSession]=useState(null),[admin,setAdmin]=useState(false),[rows,setRows]=useState([]),[emails,setEmails]=useState([]),[newEmail,setNewEmail]=useState(''),[fileName,setFileName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const s=getSupabase();setSb(s);if(!s)return;s.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=s.auth.onAuthStateChange((_e,se)=>setSession(se));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(sb&&session)check()},[sb,session]);
 async function check(){const {data:p}=await sb.from('profiles').select('is_admin').eq('id',session.user.id).maybeSingle();setAdmin(!!p?.is_admin);if(p?.is_admin){const {data:e}=await sb.from('admin_emails').select('*').order('email');setEmails(e||[]);}}
 async function importFile(e){const f=e.target.files?.[0];if(!f||!admin)return;setBusy(true);setFileName(f.name);setMsg('Membaca spreadsheet...');try{const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const data=XLSX.utils.sheet_to_json(ws,{defval:''});const mapped=data.map(r=>({contract:clean(r['NO KONTRAK']||r['No Kontrak']||r['contract']),name:clean(r['NAMA KONSUMEN']||r['Customer Name']||r['Nama Konsumen']||r['name']),priority:clean(r['DATA PRIORITY']||r['priority']),pa:clean(r['PA']||r['pa']),address:clean(r['ALAMAT']||r['Residence Address']||r['address']),village:clean(r['KELURAHAN']||r['village']),district:clean(r['KECAMATAN']||r['district']),map:clean(r['GOOGLE MAP']||r['Google Map']||r['map']),rating:clean(r['RATING']||r['rating']),visit_status:mapStatus(r['CEK VISIT']||r['STATUS VISIT']||r['Status Visit']||r['BERTEMU/TIDAK BERTEMU'])})).filter(r=>r.contract&&r.name);if(!mapped.length)throw new Error('Kolom wajib NO KONTRAK dan NAMA KONSUMEN tidak ditemukan.');setRows(mapped);setMsg(`Siap mengupdate ${mapped.length} customer. Status diambil dari kolom CEK VISIT/STATUS VISIT.`)}catch(err){setMsg(err.message)}finally{setBusy(false)}}
 async function saveImport(){if(!rows.length)return;setBusy(true);setMsg('Mengupdate database...');const {error}=await sb.from('customers').upsert(rows,{onConflict:'contract'});if(error)setMsg(error.message);else setMsg(`Berhasil mengupdate ${rows.length} customer.`);setBusy(false)}
 async function addEmail(){const email=newEmail.trim().toLowerCase();if(!email)return;const {error}=await sb.from('admin_emails').insert({email});if(error)setMsg(error.message);else{setNewEmail('');setMsg('Email admin ditambahkan.');check()}}
 async function removeEmail(id){if(!confirm('Hapus email admin ini?'))return;const {error}=await sb.from('admin_emails').delete().eq('id',id);if(error)setMsg(error.message);else check()}
 if(!session)return <main className="loginPage"><div className="loginCard"><div className="logo">WOM</div><h1>Admin</h1><p>Silakan masuk menggunakan Google.</p><a className="google" href="/">Kembali ke login</a></div></main>;
 if(!admin)return <main className="loginPage"><div className="loginCard"><h1>Akses Ditolak</h1><p>Akun <b>{session.user.email}</b> belum terdaftar sebagai admin.</p><a className="ghostBtn" href="/">Kembali</a></div></main>;
 return <main><header><div className="brand"><div className="logo">WOM</div><div><h1>Admin Visit Control</h1><p>Kelola spreadsheet, status visit, dan akses admin</p></div></div><a className="ghost" href="/">Dashboard</a></header><section className="adminGrid"><div className="card"><span className="eyebrow">UPDATE DATA</span><h2>Upload Spreadsheet</h2><p>Upload Excel terbaru. Sistem akan mencocokkan berdasarkan <b>NO KONTRAK</b> dan memperbarui status <b>Bertemu / Tidak Bertemu</b>.</p><label className="upload"><input type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/>{fileName||'Pilih file Excel'}</label>{rows.length>0&&<><div className="preview">{rows.slice(0,5).map(r=><div key={r.contract}><b>{r.name}</b><span>{r.contract} · {r.visit_status||'Belum Diupdate'}</span></div>)}</div><button className="primary wide" disabled={busy} onClick={saveImport}>{busy?'Memproses...':`Update ${rows.length} Customer`}</button></>}<div className="notice">Kolom nomor telepon tidak diproses ke tampilan pengguna. Data nomor telepon sebaiknya disimpan pada tabel/kolom yang hanya dapat diakses admin.</div>{msg&&<div className="message">{msg}</div>}</div><div className="card"><span className="eyebrow">ACCESS CONTROL</span><h2>Admin Google</h2><p>Hanya email Google yang tercantum di bawah yang menjadi admin.</p><div className="emailAdd"><input value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="email@gmail.com"/><button className="primary" onClick={addEmail}>Tambah</button></div><div className="emailList">{emails.map(e=><div key={e.id}><span>{e.email}</span><button className="danger" onClick={()=>removeEmail(e.id)}>Hapus</button></div>)}</div></div></section></main>;
}
