'use client';
import {useEffect,useMemo,useState} from 'react';
import {getSupabase} from '../lib/supabase';

const statuses=['Semua','Bertemu','Tidak Bertemu','Belum Diupdate'];
const norm=s=>(s??'').toString().trim().toLowerCase();
export default function Home(){
 const [supabase,setSupabase]=useState(null),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[data,setData]=useState([]),[q,setQ]=useState(''),[rating,setRating]=useState('Semua'),[status,setStatus]=useState('Semua'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const s=getSupabase();setSupabase(s);if(!s){setLoading(false);return;}s.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=s.auth.onAuthStateChange((_e,ses)=>setSession(ses));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase||!session)return;load()},[supabase,session]);
 async function load(){setLoading(true);setError('');const {data:d,error:e}=await supabase.from('customer_public').select('*').order('name');if(e)setError(e.message);else setData(d||[]);setLoading(false);}
 async function login(){if(!supabase)return alert('Supabase belum dikonfigurasi.');await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}})}
 async function logout(){await supabase?.auth.signOut()}
 useEffect(()=>{if(!supabase||!session)return;supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle().then(({data})=>setProfile(data))},[supabase,session]);
 const ratings=useMemo(()=>['Semua',...Array.from(new Set(data.map(x=>x.rating).filter(Boolean)))],[data]);
 const filtered=useMemo(()=>data.filter(x=>{const hay=norm([x.name,x.contract,x.address,x.village,x.district].join(' '));return(!q||hay.includes(norm(q)))&&(rating==='Semua'||x.rating===rating)&&(status==='Semua'||(status==='Belum Diupdate'?!x.visit_status:(x.visit_status===status)))}),[data,q,rating,status]);
 const stats=useMemo(()=>({total:data.length,met:data.filter(x=>x.visit_status==='Bertemu').length,notmet:data.filter(x=>x.visit_status==='Tidak Bertemu').length,pending:data.filter(x=>!x.visit_status).length}),[data]);
 if(!session)return <main className="loginPage"><div className="loginCard"><div className="logo">WOM</div><span className="eyebrow">FIELD MONITORING</span><h1>Visit Control Kendal</h1><p>Monitoring customer berdasarkan data spreadsheet. Status bertemu/tidak bertemu diperbarui oleh admin.</p>{!supabase&&<div className="notice">Aplikasi belum terhubung ke Supabase. Isi Environment Variables di Vercel terlebih dahulu.</div>}<button className="google" onClick={login} disabled={!supabase}>Masuk dengan Google</button><small>Nomor telepon hanya dapat dilihat oleh akun admin.</small></div></main>;
 return <main><header><div className="brand"><div className="logo">WOM</div><div><h1>Visit Control</h1><p>WOM Finance Kendal · September 2026</p></div></div><div className="headActions">{profile?.is_admin&&<a className="primary" href="/admin">Admin</a>}<span className="userEmail">{session.user.email}</span><button className="ghost" onClick={logout}>Keluar</button></div></header>
 <section className="hero"><div><span className="eyebrow">SPREADSHEET MONITORING</span><h2>Kontrol aktivitas visit tim</h2><p>Status customer diperbarui melalui spreadsheet oleh admin. Pengguna tidak perlu mengisi form visit.</p></div><div className="stats"><div><strong>{stats.total}</strong><span>Total</span></div><div><strong>{stats.met}</strong><span>Bertemu</span></div><div><strong>{stats.notmet}</strong><span>Tidak Bertemu</span></div><div><strong>{stats.pending}</strong><span>Belum Update</span></div></div></section>
 <section className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, kontrak, alamat..."/><select value={rating} onChange={e=>setRating(e.target.value)}>{ratings.map(r=><option key={r}>{r}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><span className="count">{filtered.length} customer</span></section>
 <section className="tableWrap"><table><thead><tr><th>Customer</th><th>No. Kontrak</th><th>Alamat</th><th>Rating</th><th>Status</th><th>Map</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty">Memuat data...</td></tr>:filtered.map(x=><tr key={x.contract}><td><b>{x.name}</b></td><td>{x.contract}<small>{x.priority||''} {x.pa?'· PA '+x.pa:''}</small></td><td>{x.address}<small>{x.village} · {x.district}</small></td><td><span className={'pill '+norm(x.rating)}>{x.rating||'-'}</span></td><td>{x.visit_status?<span className={x.visit_status==='Bertemu'?'done':'pending'}>● {x.visit_status}</span>:<span className="muted">● Belum Diupdate</span>}</td><td>{x.map&&<a href={x.map} target="_blank" rel="noreferrer">📍 Map</a>}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="6" className="empty">Data tidak ditemukan.</td></tr>}</tbody></table></section>
 {error&&<div className="error">{error}</div>}
 </main>
}
